name: Notify Testing

on:
  workflow_dispatch:
    inputs:
      staging_url:
        description: "Staging preview URL"
        required: true
        type: string

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Show URL
        run: |
          echo "Staging is ready at: ${{ github.event.inputs.staging_url }}"